runtime: custom
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker run:app

handlers:
  - url: /.*
    script: auto