[tool.poetry]
name = "gcp-streaming-pipeline"
version = "v1.0.0"
description = "Complete ETL and scalable solution using GCP "
authors = ["IvanildoBarauna <ivanildo.jnr@outlook.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0.3"
google-cloud-pubsub = "^2.22.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
coverage = "^7.5.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"