name: Execute BigQuery Query

on:
#  schedule:
#    - cron: '*/15 * * * *'
  workflow_dispatch:


jobs:
  run-query:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ivanildobarauna



      - name: Run BigQuery query
        run: |
          bq query --use_legacy_sql=false < query.sql
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    environment:
      name: gcp-cloud-run-production
